name: check

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true

      - name: Build
        run: |
          make build
          make build-windows

      - name: Test
        run: make test
